name: Lint
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: pylint
        shell: bash -l {0}
        run: |
          pylint echemdb-converters
      - name: black
        shell: bash -l {0}
        run: |
          black --check --diff echemdb-converters
      - name: isort
        shell: bash -l {0}
        run: |
          isort --check --diff --profile black echemdb-converters
